// Generated by design-lab/render.mjs. Edit design-lab/*.mjs and re-render.
export type DesignPiece = { slug: string; title: string; note: string; width: number; height: number };
export type DesignBrand = {
  key: string; name: string; real: boolean; what: string; year: string; role: string; brief: string;
  palette: Record<string, string>; fonts: { display: string; body: string };
  markLight: string; markDark: string; pieces: DesignPiece[];
};
export const brandOrder = ["keri","voyagea","dwello","beamfall","ptri","ak","trik","skyvage","riverside","ambassador","pol","honey","ferry","bakery"];
export const designBrands: Record<string, DesignBrand> = {
  "keri": {
    "key": "keri",
    "name": "Keri in Windsor",
    "real": true,
    "what": "Seasonal Indian mango brand, Windsor–Essex",
    "year": "2025",
    "role": "Brand direction, identity, packaging, campaign creative",
    "brief": "Keri means mango in Gujarati. The mark is a Kesar mango with its own highlight, shaped like the Windsor sun that ripens the season, and a single leaf for freshness. Fraunces italic gives the wordmark the softness of fruit; a tracked Manrope descriptor keeps the place name matter-of-fact.",
    "palette": {
      "kesar": "#F5A623",
      "pulp": "#FFCB5C",
      "leaf": "#1F4D2B",
      "blush": "#E8562A",
      "cream": "#FBF3E4",
      "ink": "#2A1A08"
    },
    "fonts": {
      "display": "Fraunces Italic",
      "body": "Manrope"
    },
    "markLight": "<svg viewBox=\"0 0 120 120\" width=\"120\" height=\"120\" xmlns=\"http://www.w3.org/2000/svg\">\n      <path d=\"M38 28C60 14 94 22 106 52c10 26 2 52-18 62-14 8-26 2-40-8C20 88 6 60 16 42c5-8 14-12 22-14Z\" fill=\"#F5A623\"/>\n      <path d=\"M34 42c8-6 18-4 24 4-8 6-18 6-24-4Z\" fill=\"#FFE2A0\" opacity=\".9\"/>\n      <path d=\"M40 26c2-16 26-24 40-14-10 14-28 18-40 14Z\" fill=\"#1F4D2B\"/>\n      <path d=\"M40 26c-4-6-6-12-6-18\" stroke=\"#1F4D2B\" stroke-width=\"3.5\" stroke-linecap=\"round\" fill=\"none\"/></svg>",
    "markDark": "<svg viewBox=\"0 0 120 120\" width=\"120\" height=\"120\" xmlns=\"http://www.w3.org/2000/svg\">\n      <path d=\"M38 28C60 14 94 22 106 52c10 26 2 52-18 62-14 8-26 2-40-8C20 88 6 60 16 42c5-8 14-12 22-14Z\" fill=\"#F5A623\"/>\n      <path d=\"M34 42c8-6 18-4 24 4-8 6-18 6-24-4Z\" fill=\"#FFE2A0\" opacity=\".9\"/>\n      <path d=\"M40 26c2-16 26-24 40-14-10 14-28 18-40 14Z\" fill=\"#7FBF8E\"/>\n      <path d=\"M40 26c-4-6-6-12-6-18\" stroke=\"#7FBF8E\" stroke-width=\"3.5\" stroke-linecap=\"round\" fill=\"none\"/></svg>",
    "pieces": [
      {
        "slug": "box",
        "title": "Twelve-piece Kesar box",
        "note": "The box is the brand's only physical touchpoint: it arrives at the door, sits on the counter for four days, and gets photographed. The lid is a solid mango; the side panel is where the pick date gets stamped by hand.",
        "width": 1600,
        "height": 1000
      },
      {
        "slug": "poster",
        "title": "Counter poster for partner grocers",
        "note": "Pinned behind the till at the two Indian grocers that take orders. The headline answers the only question customers ask, and the delivery days are set as a single sentence because that is how staff repeat it.",
        "width": 1200,
        "height": 1500
      },
      {
        "slug": "story",
        "title": "Season-opening story",
        "note": "The one post that does the year's work. A single date, one action, and the fruit at a scale no feed can ignore. Runs as a story and a pinned post the week before the first shipment lands.",
        "width": 1600,
        "height": 1000
      },
      {
        "slug": "tote",
        "title": "Delivery tote",
        "note": "Boxes go out in a cotton tote that customers keep. One-colour print of the lockup over the pattern, so it costs less than the box it carries.",
        "width": 1600,
        "height": 1000
      },
      {
        "slug": "type",
        "title": "Type and colour",
        "note": "",
        "width": 1600,
        "height": 1000
      }
    ]
  },
  "voyagea": {
    "key": "voyagea",
    "name": "Voyagea",
    "real": true,
    "what": "Free AI travel planner",
    "year": "2026",
    "role": "Product identity, app icon, in-app V-Passport stamps, launch creative",
    "brief": "A route that draws a V and ends at a pin. The dashed leg is the plan; the solid leg is the trip you took. It survives at 29 px on a home screen because there is nothing else in it. Playfair Display gives the wordmark the weight of a printed atlas; the dawn-orange on midnight-blue palette is the hour most trips begin.",
    "palette": {
      "dawn": "#FF7A3D",
      "dusk": "#1C2A5A",
      "sky": "#2E6BC4",
      "paper": "#F6F1E7",
      "ink": "#141A2E"
    },
    "fonts": {
      "display": "Playfair Display",
      "body": "Manrope"
    },
    "markLight": "<svg viewBox=\"0 0 120 120\" width=\"120\" height=\"120\" xmlns=\"http://www.w3.org/2000/svg\">\n      \n      <path d=\"M28 34 60 92 92 34\" fill=\"none\" stroke=\"#1C2A5A\" stroke-width=\"9\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-dasharray=\"1 16\"/>\n      <path d=\"M28 34 60 92\" fill=\"none\" stroke=\"#1C2A5A\" stroke-width=\"9\" stroke-linecap=\"round\"/>\n      <circle cx=\"92\" cy=\"34\" r=\"10\" fill=\"#FF7A3D\"/><circle cx=\"92\" cy=\"34\" r=\"4\" fill=\"#1C2A5A\"/></svg>",
    "markDark": "<svg viewBox=\"0 0 120 120\" width=\"120\" height=\"120\" xmlns=\"http://www.w3.org/2000/svg\">\n      \n      <path d=\"M28 34 60 92 92 34\" fill=\"none\" stroke=\"#FF7A3D\" stroke-width=\"9\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-dasharray=\"1 16\"/>\n      <path d=\"M28 34 60 92\" fill=\"none\" stroke=\"#FF7A3D\" stroke-width=\"9\" stroke-linecap=\"round\"/>\n      <circle cx=\"92\" cy=\"34\" r=\"10\" fill=\"#F6F1E7\"/><circle cx=\"92\" cy=\"34\" r=\"4\" fill=\"#FF7A3D\"/></svg>",
    "pieces": [
      {
        "slug": "icon",
        "title": "App icon on the home screen",
        "note": "The icon has to hold its own next to Maps and Instagram, which is why there is nothing in it but the route and the pin. Tested at 60 px before anything else was drawn.",
        "width": 1600,
        "height": 1000
      },
      {
        "slug": "story",
        "title": "Boarding-pass story",
        "note": "An Instagram story that shows the product outcome instead of the product. The itinerary is real output, trimmed to the moments people screenshot.",
        "width": 1600,
        "height": 1000
      },
      {
        "slug": "stamps",
        "title": "V-Passport stamp set",
        "note": "Digital stamps for the in-app passport, mocked as a physical sticker sheet. Each city is one landmark reduced to a few strokes; a stamp only unlocks with a verified visit.",
        "width": 1600,
        "height": 1000
      },
      {
        "slug": "poster",
        "title": "Launch poster",
        "note": "For hostels and co-working spaces in the first three cities. The headline is the product promise verbatim; the pattern behind it is the route motif at ten percent.",
        "width": 1200,
        "height": 1500
      },
      {
        "slug": "type",
        "title": "Type and colour",
        "note": "",
        "width": 1600,
        "height": 1000
      }
    ]
  },
  "dwello": {
    "key": "dwello",
    "name": "Dwello",
    "real": true,
    "what": "Presence-aware desk robot",
    "year": "2026",
    "role": "Product and character design, logotype, expression system, packaging",
    "brief": "The last letter of the logotype is the robot. Its face uses the same geometry as the physical product, so the wordmark and the object look at you the same way. Expressions are parameters rather than drawings: brow lift, brow tilt, eye openness and mouth, and it is the asymmetry between the two sides that carries most of the feeling.",
    "palette": {
      "shell": "#F4F4F2",
      "ink": "#15171C",
      "cyan": "#3EE0D8",
      "slate": "#2A2E38",
      "mist": "#D9DDE3"
    },
    "fonts": {
      "display": "Sora Bold",
      "body": "Manrope"
    },
    "markLight": "<svg viewBox=\"0 0 120 120\" width=\"120\" height=\"120\" xmlns=\"http://www.w3.org/2000/svg\"><rect x=\"6\" y=\"6\" width=\"108\" height=\"108\" rx=\"40\" fill=\"#15171C\"/><path d=\"M31 40 L53 40\" stroke=\"#F4F4F2\" stroke-width=\"4\" stroke-linecap=\"round\"/><path d=\"M67 40 L89 40\" stroke=\"#F4F4F2\" stroke-width=\"4\" stroke-linecap=\"round\"/><rect x=\"35\" y=\"40\" width=\"14\" height=\"27\" rx=\"7\" fill=\"#F4F4F2\"/><rect x=\"71\" y=\"40\" width=\"14\" height=\"27\" rx=\"7\" fill=\"#F4F4F2\"/><path d=\"M46 76c6 6 22 6 28 0\" stroke=\"#F4F4F2\" stroke-width=\"4\" stroke-linecap=\"round\" fill=\"none\"/></svg>",
    "markDark": "<svg viewBox=\"0 0 120 120\" width=\"120\" height=\"120\" xmlns=\"http://www.w3.org/2000/svg\"><rect x=\"6\" y=\"6\" width=\"108\" height=\"108\" rx=\"40\" fill=\"#F4F4F2\"/><path d=\"M31 40 L53 40\" stroke=\"#15171C\" stroke-width=\"4\" stroke-linecap=\"round\"/><path d=\"M67 40 L89 40\" stroke=\"#15171C\" stroke-width=\"4\" stroke-linecap=\"round\"/><rect x=\"35\" y=\"40\" width=\"14\" height=\"27\" rx=\"7\" fill=\"#15171C\"/><rect x=\"71\" y=\"40\" width=\"14\" height=\"27\" rx=\"7\" fill=\"#15171C\"/><path d=\"M46 76c6 6 22 6 28 0\" stroke=\"#15171C\" stroke-width=\"4\" stroke-linecap=\"round\" fill=\"none\"/></svg>",
    "pieces": [
      {
        "slug": "box",
        "title": "Retail box",
        "note": "White box, black face, nothing else on the front. The side panel does the explaining because the front already has a personality. The face on the lid winks when you open it.",
        "width": 1600,
        "height": 1000
      },
      {
        "slug": "expressions",
        "title": "Expression sheet poster",
        "note": "Printed for the workshop wall so the firmware, the industrial design and the marketing all reference the same eight faces.",
        "width": 1200,
        "height": 1500
      },
      {
        "slug": "cards",
        "title": "Team cards",
        "note": "Every card carries a different expression on the back, chosen by the person. The front is only the logotype.",
        "width": 1600,
        "height": 1000
      },
      {
        "slug": "tag",
        "title": "Hang tag",
        "note": "Ties to the power cable in the box. Says the one thing that matters before anything else is read.",
        "width": 1600,
        "height": 1000
      },
      {
        "slug": "type",
        "title": "Type and colour",
        "note": "",
        "width": 1600,
        "height": 1000
      }
    ]
  },
  "beamfall": {
    "key": "beamfall",
    "name": "BeamFall",
    "real": true,
    "what": "Light-routing puzzle for iPhone",
    "year": "2026",
    "role": "Game identity, app icon, App Store creative, launch poster",
    "brief": "Three beams meet a prism. The icon is a literal game state: cyan enters, magenta exits upward, amber continues, and the white dot is the point where you tap. Unbounded at two weights splits the name into the beam and the fall. Everything on every piece is a real game element, so the brand never has to invent decoration.",
    "palette": {
      "void": "#07070C",
      "cyan": "#3DF1FF",
      "magenta": "#FF3DAA",
      "amber": "#FFC53D",
      "glass": "#1A1B2E",
      "steel": "#8A8FB0"
    },
    "fonts": {
      "display": "Unbounded",
      "body": "Space Grotesk"
    },
    "markLight": "<svg viewBox=\"0 0 120 120\" width=\"120\" height=\"120\" xmlns=\"http://www.w3.org/2000/svg\">\n      <rect width=\"120\" height=\"120\" rx=\"28\" fill=\"#12131F\"/>\n      <path d=\"M0 60H50L60 50\" stroke=\"#3DF1FF\" stroke-width=\"6\" fill=\"none\"/>\n      <path d=\"M60 50L60 0\" stroke=\"#FF3DAA\" stroke-width=\"6\" fill=\"none\"/>\n      <path d=\"M60 50L120 50\" stroke=\"#FFC53D\" stroke-width=\"6\" fill=\"none\"/>\n      <path d=\"M44 66 60 34 76 66Z\" fill=\"#1A1B2E\" stroke=\"#8A8FB0\" stroke-width=\"2\"/>\n      <circle cx=\"60\" cy=\"50\" r=\"5\" fill=\"#fff\"/></svg>",
    "markDark": "<svg viewBox=\"0 0 120 120\" width=\"120\" height=\"120\" xmlns=\"http://www.w3.org/2000/svg\">\n      <rect width=\"120\" height=\"120\" rx=\"28\" fill=\"#12131F\"/>\n      <path d=\"M0 60H50L60 50\" stroke=\"#3DF1FF\" stroke-width=\"6\" fill=\"none\"/>\n      <path d=\"M60 50L60 0\" stroke=\"#FF3DAA\" stroke-width=\"6\" fill=\"none\"/>\n      <path d=\"M60 50L120 50\" stroke=\"#FFC53D\" stroke-width=\"6\" fill=\"none\"/>\n      <path d=\"M44 66 60 34 76 66Z\" fill=\"#1A1B2E\" stroke=\"#8A8FB0\" stroke-width=\"2\"/>\n      <circle cx=\"60\" cy=\"50\" r=\"5\" fill=\"#fff\"/></svg>",
    "pieces": [
      {
        "slug": "icon",
        "title": "App icon on the home screen",
        "note": "A literal game state as an icon: cyan in, magenta up, amber on, and the white tap point. It reads at 60 px because the beams are the only shapes in it.",
        "width": 1600,
        "height": 1000
      },
      {
        "slug": "poster",
        "title": "Launch poster",
        "note": "Three beams, one prism, and the title where the light lands. Framed for the studio; printed on black stock so the grid disappears into the paper.",
        "width": 1200,
        "height": 1500
      },
      {
        "slug": "screen",
        "title": "App Store screenshot",
        "note": "The first store screenshot shows a mid-solve state rather than a splash, because the puzzle is the pitch.",
        "width": 1600,
        "height": 1000
      },
      {
        "slug": "stickers",
        "title": "Piece stickers",
        "note": "A sticker pack of the six game pieces, given out at the launch meet-up. Each is the exact glyph from the game's legend.",
        "width": 1600,
        "height": 1000
      },
      {
        "slug": "type",
        "title": "Type and colour",
        "note": "",
        "width": 1600,
        "height": 1000
      }
    ]
  },
  "ptri": {
    "key": "ptri",
    "name": "PTRI Innovation",
    "real": true,
    "what": "AI-first technology company",
    "year": "2026",
    "role": "Monogram, stationery, presentation system",
    "brief": "The P is a constellation: six nodes joined by hairlines, with one ember node where the letter turns. It reads as a mark first and as a letter second, which is the right order for a company that builds systems rather than sells a name. Space Grotesk carries the wordmark; Playfair italic carries the word innovation, so the two halves of the company sit in one line.",
    "palette": {
      "space": "#0B0B14",
      "ember": "#FF6A1F",
      "star": "#F2EEE6",
      "nebula": "#3A2A6A",
      "slate": "#20222F"
    },
    "fonts": {
      "display": "Playfair Display Italic",
      "body": "Space Grotesk"
    },
    "markLight": "<svg viewBox=\"0 0 120 120\" width=\"120\" height=\"120\" xmlns=\"http://www.w3.org/2000/svg\"><polyline points=\"30,96 30,24 70,24 88,42 70,60 30,60\" fill=\"none\" stroke=\"#0B0B14\" stroke-width=\"2.5\" stroke-linejoin=\"round\"/><circle cx=\"30\" cy=\"96\" r=\"6\" fill=\"#0B0B14\"/><circle cx=\"30\" cy=\"24\" r=\"4\" fill=\"#0B0B14\"/><circle cx=\"70\" cy=\"24\" r=\"4\" fill=\"#0B0B14\"/><circle cx=\"88\" cy=\"42\" r=\"6\" fill=\"#FF6A1F\"/><circle cx=\"70\" cy=\"60\" r=\"4\" fill=\"#0B0B14\"/><circle cx=\"30\" cy=\"60\" r=\"4\" fill=\"#0B0B14\"/></svg>",
    "markDark": "<svg viewBox=\"0 0 120 120\" width=\"120\" height=\"120\" xmlns=\"http://www.w3.org/2000/svg\"><polyline points=\"30,96 30,24 70,24 88,42 70,60 30,60\" fill=\"none\" stroke=\"#F2EEE6\" stroke-width=\"2.5\" stroke-linejoin=\"round\"/><circle cx=\"30\" cy=\"96\" r=\"6\" fill=\"#F2EEE6\"/><circle cx=\"30\" cy=\"24\" r=\"4\" fill=\"#F2EEE6\"/><circle cx=\"70\" cy=\"24\" r=\"4\" fill=\"#F2EEE6\"/><circle cx=\"88\" cy=\"42\" r=\"6\" fill=\"#FF6A1F\"/><circle cx=\"70\" cy=\"60\" r=\"4\" fill=\"#F2EEE6\"/><circle cx=\"30\" cy=\"60\" r=\"4\" fill=\"#F2EEE6\"/></svg>",
    "pieces": [
      {
        "slug": "cards",
        "title": "Business cards",
        "note": "Front carries only the constellation. The back holds everything in one column so the card reads like a line of a terminal.",
        "width": 1600,
        "height": 1000
      },
      {
        "slug": "poster",
        "title": "Office poster",
        "note": "The monogram at the size it was designed for. Hangs in the Ahmedabad office reception.",
        "width": 1200,
        "height": 1500
      },
      {
        "slug": "stationery",
        "title": "Stationery",
        "note": "Letterhead on warm white, envelope in space black, and an ember compliment slip that is the only place the accent colour is allowed to fill a surface.",
        "width": 1600,
        "height": 1000
      },
      {
        "slug": "wallpaper",
        "title": "Team wallpaper",
        "note": "The lock screen for company phones. The pattern is the constellation at twelve percent, so the mark has somewhere to sit.",
        "width": 1600,
        "height": 1000
      },
      {
        "slug": "type",
        "title": "Type and colour",
        "note": "",
        "width": 1600,
        "height": 1000
      }
    ]
  },
  "ak": {
    "key": "ak",
    "name": "AK Builds & Plumbing",
    "real": true,
    "what": "Renovation and plumbing, Windsor",
    "year": "2026",
    "role": "Badge, wordmark, vehicle livery, workwear, site signage",
    "brief": "A roofline, the initials, and a pipe elbow inside one ring: the two halves of the business in a single badge. It was drawn to be embroidered on a work shirt, so nothing in it is thinner than a stitch. Archivo Black carries the name at any distance; navy and brass read as trade, not tech.",
    "palette": {
      "navy": "#10243E",
      "brass": "#C89B3C",
      "white": "#F7F5F0",
      "red": "#B5341C",
      "steel": "#8A93A0"
    },
    "fonts": {
      "display": "Archivo Black",
      "body": "Rubik"
    },
    "markLight": "<svg viewBox=\"0 0 120 120\" width=\"120\" height=\"120\" xmlns=\"http://www.w3.org/2000/svg\">\n      <circle cx=\"60\" cy=\"60\" r=\"56\" fill=\"none\" stroke=\"#10243E\" stroke-width=\"4\"/>\n      <circle cx=\"60\" cy=\"60\" r=\"49\" fill=\"none\" stroke=\"#10243E\" stroke-width=\"1.5\" stroke-dasharray=\"2 4\"/>\n      <path d=\"M26 54 60 28l34 26\" fill=\"none\" stroke=\"#C89B3C\" stroke-width=\"6\" stroke-linejoin=\"round\" stroke-linecap=\"round\"/>\n      <text x=\"60\" y=\"76\" text-anchor=\"middle\" font-family=\"'Archivo Black',sans-serif\" font-size=\"34\" fill=\"#10243E\">AK</text>\n      <path d=\"M38 92h18v-8h8v8h18\" fill=\"none\" stroke=\"#C89B3C\" stroke-width=\"5\" stroke-linejoin=\"round\"/></svg>",
    "markDark": "<svg viewBox=\"0 0 120 120\" width=\"120\" height=\"120\" xmlns=\"http://www.w3.org/2000/svg\">\n      <circle cx=\"60\" cy=\"60\" r=\"56\" fill=\"none\" stroke=\"#F7F5F0\" stroke-width=\"4\"/>\n      <circle cx=\"60\" cy=\"60\" r=\"49\" fill=\"none\" stroke=\"#F7F5F0\" stroke-width=\"1.5\" stroke-dasharray=\"2 4\"/>\n      <path d=\"M26 54 60 28l34 26\" fill=\"none\" stroke=\"#C89B3C\" stroke-width=\"6\" stroke-linejoin=\"round\" stroke-linecap=\"round\"/>\n      <text x=\"60\" y=\"76\" text-anchor=\"middle\" font-family=\"'Archivo Black',sans-serif\" font-size=\"34\" fill=\"#F7F5F0\">AK</text>\n      <path d=\"M38 92h18v-8h8v8h18\" fill=\"none\" stroke=\"#C89B3C\" stroke-width=\"5\" stroke-linejoin=\"round\"/></svg>",
    "pieces": [
      {
        "slug": "site-sign",
        "title": "Site sign",
        "note": "Goes on the lawn of every job for the length of the job. The phone number is the biggest thing on it because that is what a neighbour needs.",
        "width": 1600,
        "height": 1000
      },
      {
        "slug": "cards",
        "title": "Business cards",
        "note": "Navy front with the badge embossed; brass-topped back with the number. Printed on 600 gsm because they get handed over with dusty hands.",
        "width": 1600,
        "height": 1000
      },
      {
        "slug": "shopfront",
        "title": "Workshop front",
        "note": "The unit on Walker Road. Navy fascia, brass-lettered, and an awning striped in the same two colours.",
        "width": 1600,
        "height": 1000
      },
      {
        "slug": "stickers",
        "title": "Hard-hat stickers",
        "note": "Four colourways of the badge, cut as 80 mm circles. They end up on toolboxes, tailgates and the odd fridge.",
        "width": 1600,
        "height": 1000
      },
      {
        "slug": "type",
        "title": "Type and colour",
        "note": "",
        "width": 1600,
        "height": 1000
      }
    ]
  },
  "trik": {
    "key": "trik",
    "name": "Trik Studio",
    "real": true,
    "what": "Interior design studio, Ahmedabad",
    "year": "2026",
    "role": "Identity, stationery, project signage, web art direction",
    "brief": "The corner of a room: floor, left wall, right wall, the three planes every interior begins with, drawn as one isometric mark. Plaster, walnut and brass are the studio's own materials rather than a chosen palette. DM Serif Display gives the wordmark a proportion that sits comfortably on a brass plate.",
    "palette": {
      "plaster": "#EFE9DE",
      "walnut": "#4A3628",
      "brass": "#B08D57",
      "ink": "#1E1A16",
      "sage": "#8A9A82"
    },
    "fonts": {
      "display": "DM Serif Display",
      "body": "Manrope"
    },
    "markLight": "<svg viewBox=\"0 0 120 120\" width=\"120\" height=\"120\" xmlns=\"http://www.w3.org/2000/svg\">\n      <path d=\"M60 14 18 38v46l42-24Z\" fill=\"#4A3628\"/>\n      <path d=\"M60 14l42 24v46L60 60Z\" fill=\"#1E1A16\"/>\n      <path d=\"M18 84l42-24 42 24-42 24Z\" fill=\"#B08D57\"/>\n      <path d=\"M60 60v48\" stroke=\"rgba(255,255,255,.35)\" stroke-width=\"1.5\"/></svg>",
    "markDark": "<svg viewBox=\"0 0 120 120\" width=\"120\" height=\"120\" xmlns=\"http://www.w3.org/2000/svg\">\n      <path d=\"M60 14 18 38v46l42-24Z\" fill=\"#EFE9DE\"/>\n      <path d=\"M60 14l42 24v46L60 60Z\" fill=\"#8A7462\"/>\n      <path d=\"M18 84l42-24 42 24-42 24Z\" fill=\"#B08D57\"/>\n      <path d=\"M60 60v48\" stroke=\"rgba(255,255,255,.35)\" stroke-width=\"1.5\"/></svg>",
    "pieces": [
      {
        "slug": "stationery",
        "title": "Stationery",
        "note": "Plaster letterhead, walnut envelope, ink card. A proposal on this paper should feel like the room it describes.",
        "width": 1600,
        "height": 1000
      },
      {
        "slug": "plate",
        "title": "Studio door plate",
        "note": "Brass on walnut at the studio entrance. The mark is deep-etched; the type is filled.",
        "width": 1600,
        "height": 1000
      },
      {
        "slug": "cards",
        "title": "Business cards",
        "note": "Ink on one side, plaster on the other, and the corner mark in brass foil.",
        "width": 1600,
        "height": 1000
      },
      {
        "slug": "poster",
        "title": "Project board",
        "note": "Placed at the site entrance during a build so the neighbours know who is doing the work.",
        "width": 1200,
        "height": 1500
      },
      {
        "slug": "type",
        "title": "Type and colour",
        "note": "",
        "width": 1600,
        "height": 1000
      }
    ]
  },
  "skyvage": {
    "key": "skyvage",
    "name": "Skyvage",
    "real": true,
    "what": "Private aviation concept site",
    "year": "2026",
    "role": "Wordmark, mark, cabin collateral, art direction",
    "brief": "A descending V with a gold delta for the aircraft: the shape of a flight path ending at a runway. The wordmark is light, wide and tracked to take up the room a cabin does. Night blue, silver and gold are the palette of a window seat after sunset.",
    "palette": {
      "night": "#0B1020",
      "silver": "#D9DEE8",
      "gold": "#D4B36A",
      "ink": "#0B1020",
      "haze": "#3B4766"
    },
    "fonts": {
      "display": "Bricolage Grotesque Light",
      "body": "Manrope"
    },
    "markLight": "<svg viewBox=\"0 0 120 120\" width=\"120\" height=\"120\" xmlns=\"http://www.w3.org/2000/svg\">\n      <path d=\"M12 36 60 98 108 36\" fill=\"none\" stroke=\"#0B1020\" stroke-width=\"11\" stroke-linejoin=\"round\" stroke-linecap=\"round\"/>\n      <path d=\"M60 96 44 56h32Z\" fill=\"#D4B36A\"/>\n      <path d=\"M28 24h64\" stroke=\"#0B1020\" stroke-width=\"3\" stroke-linecap=\"round\" opacity=\".6\"/></svg>",
    "markDark": "<svg viewBox=\"0 0 120 120\" width=\"120\" height=\"120\" xmlns=\"http://www.w3.org/2000/svg\">\n      <path d=\"M12 36 60 98 108 36\" fill=\"none\" stroke=\"#D9DEE8\" stroke-width=\"11\" stroke-linejoin=\"round\" stroke-linecap=\"round\"/>\n      <path d=\"M60 96 44 56h32Z\" fill=\"#D4B36A\"/>\n      <path d=\"M28 24h64\" stroke=\"#D9DEE8\" stroke-width=\"3\" stroke-linecap=\"round\" opacity=\".6\"/></svg>",
    "pieces": [
      {
        "slug": "tag",
        "title": "Cabin luggage tag",
        "note": "Night blue leather, silver foil, one gold delta. The tag is the only physical thing a passenger keeps.",
        "width": 1600,
        "height": 1000
      },
      {
        "slug": "story",
        "title": "Rates story",
        "note": "The whole brand argument in one screen: a number where other charter brands put a form.",
        "width": 1600,
        "height": 1000
      },
      {
        "slug": "cards",
        "title": "Boarding cards",
        "note": "A boarding card the size of a business card. Silver on night, gold for the seat.",
        "width": 1600,
        "height": 1000
      },
      {
        "slug": "poster",
        "title": "Lounge poster",
        "note": "For the FBO lounge wall. Two words, because the people in that room already know what the aircraft costs.",
        "width": 1200,
        "height": 1500
      },
      {
        "slug": "type",
        "title": "Type and colour",
        "note": "",
        "width": 1600,
        "height": 1000
      }
    ]
  },
  "riverside": {
    "key": "riverside",
    "name": "Riverside Roasters",
    "real": false,
    "what": "Concept: a Windsor coffee roaster on the Detroit River",
    "year": "2026",
    "role": "Concept identity, packaging, storefront, coasters",
    "brief": "A cup seen from above with the river running through it, and three lines of steam that are the only thing to break the circle. Libre Caslon gives it the voice of a place that has been open a while; river teal on roast brown is the view from the counter.",
    "palette": {
      "roast": "#3B2416",
      "river": "#2F6E73",
      "foam": "#F3EBDD",
      "copper": "#C8763A",
      "kraft": "#B98F63"
    },
    "fonts": {
      "display": "Libre Caslon Text",
      "body": "Manrope"
    },
    "markLight": "<svg viewBox=\"0 0 120 120\" width=\"120\" height=\"120\" xmlns=\"http://www.w3.org/2000/svg\">\n      <circle cx=\"60\" cy=\"60\" r=\"50\" fill=\"none\" stroke=\"#3B2416\" stroke-width=\"6\"/>\n      <clipPath id=\"rrpg3i8\"><circle cx=\"60\" cy=\"60\" r=\"47\"/></clipPath>\n      <g clip-path=\"url(#rrpg3i8)\" fill=\"none\" stroke=\"#2F6E73\" stroke-width=\"5\" stroke-linecap=\"round\">\n        <path d=\"M6 66c12-10 24-10 36 0s24 10 36 0 24-10 36 0\"/>\n        <path d=\"M6 82c12-10 24-10 36 0s24 10 36 0 24-10 36 0\" opacity=\".55\"/>\n      </g>\n      <path d=\"M44 40c-4-8 4-10 0-18M60 40c-4-8 4-10 0-18M76 40c-4-8 4-10 0-18\" stroke=\"#3B2416\" stroke-width=\"3.5\" stroke-linecap=\"round\" fill=\"none\"/></svg>",
    "markDark": "<svg viewBox=\"0 0 120 120\" width=\"120\" height=\"120\" xmlns=\"http://www.w3.org/2000/svg\">\n      <circle cx=\"60\" cy=\"60\" r=\"50\" fill=\"none\" stroke=\"#F3EBDD\" stroke-width=\"6\"/>\n      <clipPath id=\"rrlg4lo\"><circle cx=\"60\" cy=\"60\" r=\"47\"/></clipPath>\n      <g clip-path=\"url(#rrlg4lo)\" fill=\"none\" stroke=\"#C8763A\" stroke-width=\"5\" stroke-linecap=\"round\">\n        <path d=\"M6 66c12-10 24-10 36 0s24 10 36 0 24-10 36 0\"/>\n        <path d=\"M6 82c12-10 24-10 36 0s24 10 36 0 24-10 36 0\" opacity=\".55\"/>\n      </g>\n      <path d=\"M44 40c-4-8 4-10 0-18M60 40c-4-8 4-10 0-18M76 40c-4-8 4-10 0-18\" stroke=\"#F3EBDD\" stroke-width=\"3.5\" stroke-linecap=\"round\" fill=\"none\"/></svg>",
    "pieces": [
      {
        "slug": "bag",
        "title": "Coffee bag",
        "note": "Kraft pouch with a river-blue band. The roast, origin and date sit in a block a Sharpie can overwrite when the label runs out.",
        "width": 1600,
        "height": 1000
      },
      {
        "slug": "shopfront",
        "title": "Storefront",
        "note": "The corner unit on Riverside Drive. Roast-brown fascia, foam lettering, and a teal awning that is the river's colour on the street.",
        "width": 1600,
        "height": 1000
      },
      {
        "slug": "coasters",
        "title": "Coasters",
        "note": "Pulpboard coasters in four colourways. The mark is the whole design; the ring is the cup.",
        "width": 1600,
        "height": 1000
      },
      {
        "slug": "cards",
        "title": "Loyalty cards",
        "note": "Ten stamps, then a free cup. The stamp is the mark's cup ring in copper ink.",
        "width": 1600,
        "height": 1000
      },
      {
        "slug": "type",
        "title": "Type and colour",
        "note": "",
        "width": 1600,
        "height": 1000
      }
    ]
  },
  "ambassador": {
    "key": "ambassador",
    "name": "Ambassador Cycles",
    "real": false,
    "what": "Concept: a riverfront bike shop named for the bridge",
    "year": "2026",
    "role": "Concept identity, storefront, ride posters, merchandise",
    "brief": "The Ambassador Bridge tower and cables over a chainring, with the deck as the line between them. Bebas Neue is the shop sign you can read from the trail at speed; signal yellow on steel blue is safety wear turned into a palette.",
    "palette": {
      "steel": "#1C2B3A",
      "signal": "#F2C230",
      "chalk": "#F5F1E8",
      "rust": "#B9482B",
      "sky": "#9DBBD3"
    },
    "fonts": {
      "display": "Bebas Neue",
      "body": "Rubik"
    },
    "markLight": "<svg viewBox=\"0 0 120 120\" width=\"120\" height=\"120\" xmlns=\"http://www.w3.org/2000/svg\">\n      <circle cx=\"84.0\" cy=\"86.0\" r=\"3\" fill=\"#1C2B3A\"/><circle cx=\"81.6\" cy=\"96.4\" r=\"3\" fill=\"#1C2B3A\"/><circle cx=\"75.0\" cy=\"104.8\" r=\"3\" fill=\"#1C2B3A\"/><circle cx=\"65.3\" cy=\"109.4\" r=\"3\" fill=\"#1C2B3A\"/><circle cx=\"54.7\" cy=\"109.4\" r=\"3\" fill=\"#1C2B3A\"/><circle cx=\"45.0\" cy=\"104.8\" r=\"3\" fill=\"#1C2B3A\"/><circle cx=\"38.4\" cy=\"96.4\" r=\"3\" fill=\"#1C2B3A\"/><circle cx=\"36.0\" cy=\"86.0\" r=\"3\" fill=\"#1C2B3A\"/><circle cx=\"38.4\" cy=\"75.6\" r=\"3\" fill=\"#1C2B3A\"/><circle cx=\"45.0\" cy=\"67.2\" r=\"3\" fill=\"#1C2B3A\"/><circle cx=\"54.7\" cy=\"62.6\" r=\"3\" fill=\"#1C2B3A\"/><circle cx=\"65.3\" cy=\"62.6\" r=\"3\" fill=\"#1C2B3A\"/><circle cx=\"75.0\" cy=\"67.2\" r=\"3\" fill=\"#1C2B3A\"/><circle cx=\"81.6\" cy=\"75.6\" r=\"3\" fill=\"#1C2B3A\"/><circle cx=\"60\" cy=\"86\" r=\"20\" fill=\"none\" stroke=\"#1C2B3A\" stroke-width=\"6\"/>\n      <circle cx=\"60\" cy=\"86\" r=\"7\" fill=\"#F2C230\"/>\n      <path d=\"M4 56h112\" stroke=\"#1C2B3A\" stroke-width=\"5\" stroke-linecap=\"round\"/>\n      <path d=\"M4 56Q30 12 56 12M64 12Q90 12 116 56\" fill=\"none\" stroke=\"#1C2B3A\" stroke-width=\"4\"/>\n      <path d=\"M54 8h4v48h-4zM62 8h4v48h-4zM54 20h12v3H54zM54 34h12v3H54z\" fill=\"#1C2B3A\"/>\n      <path d=\"M22 56V40M36 56V22M84 56V22M98 56V40\" stroke=\"#1C2B3A\" stroke-width=\"2.5\"/></svg>",
    "markDark": "<svg viewBox=\"0 0 120 120\" width=\"120\" height=\"120\" xmlns=\"http://www.w3.org/2000/svg\">\n      <circle cx=\"84.0\" cy=\"86.0\" r=\"3\" fill=\"#F5F1E8\"/><circle cx=\"81.6\" cy=\"96.4\" r=\"3\" fill=\"#F5F1E8\"/><circle cx=\"75.0\" cy=\"104.8\" r=\"3\" fill=\"#F5F1E8\"/><circle cx=\"65.3\" cy=\"109.4\" r=\"3\" fill=\"#F5F1E8\"/><circle cx=\"54.7\" cy=\"109.4\" r=\"3\" fill=\"#F5F1E8\"/><circle cx=\"45.0\" cy=\"104.8\" r=\"3\" fill=\"#F5F1E8\"/><circle cx=\"38.4\" cy=\"96.4\" r=\"3\" fill=\"#F5F1E8\"/><circle cx=\"36.0\" cy=\"86.0\" r=\"3\" fill=\"#F5F1E8\"/><circle cx=\"38.4\" cy=\"75.6\" r=\"3\" fill=\"#F5F1E8\"/><circle cx=\"45.0\" cy=\"67.2\" r=\"3\" fill=\"#F5F1E8\"/><circle cx=\"54.7\" cy=\"62.6\" r=\"3\" fill=\"#F5F1E8\"/><circle cx=\"65.3\" cy=\"62.6\" r=\"3\" fill=\"#F5F1E8\"/><circle cx=\"75.0\" cy=\"67.2\" r=\"3\" fill=\"#F5F1E8\"/><circle cx=\"81.6\" cy=\"75.6\" r=\"3\" fill=\"#F5F1E8\"/><circle cx=\"60\" cy=\"86\" r=\"20\" fill=\"none\" stroke=\"#F5F1E8\" stroke-width=\"6\"/>\n      <circle cx=\"60\" cy=\"86\" r=\"7\" fill=\"#F2C230\"/>\n      <path d=\"M4 56h112\" stroke=\"#F5F1E8\" stroke-width=\"5\" stroke-linecap=\"round\"/>\n      <path d=\"M4 56Q30 12 56 12M64 12Q90 12 116 56\" fill=\"none\" stroke=\"#F5F1E8\" stroke-width=\"4\"/>\n      <path d=\"M54 8h4v48h-4zM62 8h4v48h-4zM54 20h12v3H54zM54 34h12v3H54z\" fill=\"#F5F1E8\"/>\n      <path d=\"M22 56V40M36 56V22M84 56V22M98 56V40\" stroke=\"#F5F1E8\" stroke-width=\"2.5\"/></svg>",
    "pieces": [
      {
        "slug": "shopfront",
        "title": "Shop front",
        "note": "The unit under the bridge approach. Steel-blue fascia with the badge cut from signal yellow acrylic.",
        "width": 1600,
        "height": 1000
      },
      {
        "slug": "poster",
        "title": "Sunday ride poster",
        "note": "Pasted on the trail bollards every Saturday night. The bridge is reduced to cables and a horizon so the type can do the shouting.",
        "width": 1200,
        "height": 1500
      },
      {
        "slug": "tote",
        "title": "Musette",
        "note": "The bag riders get with a service. Badge in one colour on unbleached cotton.",
        "width": 1600,
        "height": 1000
      },
      {
        "slug": "stickers",
        "title": "Frame stickers",
        "note": "Four badge colourways for down tubes and helmets.",
        "width": 1600,
        "height": 1000
      },
      {
        "slug": "type",
        "title": "Type and colour",
        "note": "",
        "width": 1600,
        "height": 1000
      }
    ]
  },
  "pol": {
    "key": "pol",
    "name": "Pol Walks",
    "real": false,
    "what": "Concept: guided walks through Ahmedabad's old-city pols",
    "year": "2026",
    "role": "Concept identity, tickets, wayfinding, tote",
    "brief": "A carved arch with a terracotta doorway: the threshold of a pol house, the thing every walk passes through a hundred times. Cormorant carries the age of the old city; Manrope carries the map. Indigo and sandstone are the city's own morning colours.",
    "palette": {
      "sandstone": "#D9A66C",
      "indigo": "#1E2A5C",
      "lime": "#F0E6C8",
      "terracotta": "#A8442B",
      "dust": "#C9B79A"
    },
    "fonts": {
      "display": "Cormorant Garamond",
      "body": "Manrope"
    },
    "markLight": "<svg viewBox=\"0 0 120 120\" width=\"120\" height=\"120\" xmlns=\"http://www.w3.org/2000/svg\">\n      <path d=\"M22 100V56c0-10 8-16 14-22 8-8 12-18 24-18s16 10 24 18c6 6 14 12 14 22v44Z\" fill=\"none\" stroke=\"#1E2A5C\" stroke-width=\"5\" stroke-linejoin=\"round\"/>\n      <path d=\"M46 100V70c0-10 6-16 14-16s14 6 14 16v30\" fill=\"#A8442B\"/>\n      <path d=\"M14 100h92M20 108h80\" stroke=\"#1E2A5C\" stroke-width=\"4\" stroke-linecap=\"round\"/>\n      <circle cx=\"60\" cy=\"34\" r=\"4\" fill=\"#1E2A5C\"/></svg>",
    "markDark": "<svg viewBox=\"0 0 120 120\" width=\"120\" height=\"120\" xmlns=\"http://www.w3.org/2000/svg\">\n      <path d=\"M22 100V56c0-10 8-16 14-22 8-8 12-18 24-18s16 10 24 18c6 6 14 12 14 22v44Z\" fill=\"none\" stroke=\"#F0E6C8\" stroke-width=\"5\" stroke-linejoin=\"round\"/>\n      <path d=\"M46 100V70c0-10 6-16 14-16s14 6 14 16v30\" fill=\"#D9A66C\"/>\n      <path d=\"M14 100h92M20 108h80\" stroke=\"#F0E6C8\" stroke-width=\"4\" stroke-linecap=\"round\"/>\n      <circle cx=\"60\" cy=\"34\" r=\"4\" fill=\"#F0E6C8\"/></svg>",
    "pieces": [
      {
        "slug": "poster",
        "title": "Walk poster",
        "note": "The route drawn as a chain of arches, because the ticket and the poster should be the same map. Pasted at the guesthouses in the old city.",
        "width": 1200,
        "height": 1500
      },
      {
        "slug": "tote",
        "title": "Walk tote",
        "note": "Handed out at the end of the walk with the chai. Indigo arch on unbleached cotton.",
        "width": 1600,
        "height": 1000
      },
      {
        "slug": "ticket",
        "title": "Tear-off ticket",
        "note": "The guide stamps an arch at each stop. By the end the ticket is a record of the walk.",
        "width": 1600,
        "height": 1000
      },
      {
        "slug": "sign",
        "title": "Pol wayfinding",
        "note": "Enamel signs at the entrance to each pol on the route. Indigo on lime with the stop number as an arch.",
        "width": 1600,
        "height": 1000
      },
      {
        "slug": "type",
        "title": "Type and colour",
        "note": "",
        "width": 1600,
        "height": 1000
      }
    ]
  },
  "honey": {
    "key": "honey",
    "name": "Tecumseh Honey Co.",
    "real": false,
    "what": "Concept: small-batch honey from Essex County",
    "year": "2026",
    "role": "Concept identity, jar labels, market signage",
    "brief": "A hexagon that holds a single drop. Fraunces at its heaviest weight has the softness of honey without turning into a cartoon; the label lists the apiary's road because customers here buy from a place, not a brand.",
    "palette": {
      "amber": "#E39B1E",
      "comb": "#5A3510",
      "wax": "#FBF1D6",
      "ink": "#2B1D0E",
      "clover": "#7A8B4E"
    },
    "fonts": {
      "display": "Fraunces Bold",
      "body": "Manrope"
    },
    "markLight": "<svg viewBox=\"0 0 120 120\" width=\"120\" height=\"120\" xmlns=\"http://www.w3.org/2000/svg\">\n      <path d=\"M60 8 104 34v52L60 112 16 86V34Z\" fill=\"none\" stroke=\"#5A3510\" stroke-width=\"5\" stroke-linejoin=\"round\"/>\n      <path d=\"M60 40c10 14 18 22 18 34a18 18 0 0 1-36 0c0-12 8-20 18-34Z\" fill=\"#E39B1E\"/></svg>",
    "markDark": "<svg viewBox=\"0 0 120 120\" width=\"120\" height=\"120\" xmlns=\"http://www.w3.org/2000/svg\">\n      <path d=\"M60 8 104 34v52L60 112 16 86V34Z\" fill=\"none\" stroke=\"#FBF1D6\" stroke-width=\"5\" stroke-linejoin=\"round\"/>\n      <path d=\"M60 40c10 14 18 22 18 34a18 18 0 0 1-36 0c0-12 8-20 18-34Z\" fill=\"#E39B1E\"/></svg>",
    "pieces": [
      {
        "slug": "jar",
        "title": "Jar label",
        "note": "A wraparound label on a 500 g jar. The hexagon holds a single drop; the road name says where it came from.",
        "width": 1600,
        "height": 1000
      },
      {
        "slug": "sign",
        "title": "Market sign",
        "note": "The Saturday market stall. One panel, one price, one place.",
        "width": 1600,
        "height": 1000
      },
      {
        "slug": "lids",
        "title": "Lid labels",
        "note": "Four varietals, four lid colours, so the shelf reads at a glance.",
        "width": 1600,
        "height": 1000
      },
      {
        "slug": "poster",
        "title": "Farm-gate poster",
        "note": "At the end of the driveway, laminated. The headline is the brand's whole argument.",
        "width": 1200,
        "height": 1500
      },
      {
        "slug": "type",
        "title": "Type and colour",
        "note": "",
        "width": 1600,
        "height": 1000
      }
    ]
  },
  "ferry": {
    "key": "ferry",
    "name": "Essex County Ferry",
    "real": false,
    "what": "Concept: wayfinding for a Windsor–Detroit passenger ferry",
    "year": "2026",
    "role": "Concept identity, pictograms, wayfinding, tickets",
    "brief": "A ferry drawn on the same grid as the pictograms it sits beside, so the logo is the first sign in the system rather than a separate thing. Navy panels, one buoy-orange accent, and Sora at heavy weights for names you read from across a terminal.",
    "palette": {
      "navy": "#0F2A44",
      "buoy": "#F25C2A",
      "white": "#FFFFFF",
      "mist": "#DCE6EE",
      "river": "#2E6C8A"
    },
    "fonts": {
      "display": "Sora Bold",
      "body": "Sora"
    },
    "markLight": "<svg viewBox=\"0 0 120 120\" width=\"120\" height=\"120\" xmlns=\"http://www.w3.org/2000/svg\">\n      <path d=\"M20 70h80l-10 18H30Z\" fill=\"#0F2A44\"/>\n      <path d=\"M36 70V48h48v22\" fill=\"#0F2A44\"/>\n      <path d=\"M44 56h8v8h-8zM56 56h8v8h-8zM68 56h8v8h-8z\" fill=\"#F25C2A\"/>\n      <path d=\"M8 98c10-8 18-8 28 0s18 8 28 0 18-8 28 0 18 8 28 0\" fill=\"none\" stroke=\"#0F2A44\" stroke-width=\"5\" stroke-linecap=\"round\"/></svg>",
    "markDark": "<svg viewBox=\"0 0 120 120\" width=\"120\" height=\"120\" xmlns=\"http://www.w3.org/2000/svg\">\n      <path d=\"M20 70h80l-10 18H30Z\" fill=\"#FFFFFF\"/>\n      <path d=\"M36 70V48h48v22\" fill=\"#FFFFFF\"/>\n      <path d=\"M44 56h8v8h-8zM56 56h8v8h-8zM68 56h8v8h-8z\" fill=\"#F25C2A\"/>\n      <path d=\"M8 98c10-8 18-8 28 0s18 8 28 0 18-8 28 0 18 8 28 0\" fill=\"none\" stroke=\"#FFFFFF\" stroke-width=\"5\" stroke-linecap=\"round\"/></svg>",
    "pieces": [
      {
        "slug": "sign",
        "title": "Terminal wayfinding",
        "note": "Navy panels, one buoy-orange accent, and the arrow as the biggest thing on every sign.",
        "width": 1600,
        "height": 1000
      },
      {
        "slug": "ticket",
        "title": "Mobile ticket",
        "note": "The ticket is the timetable: the next sailing is the biggest number on the screen, and the barcode is the only other thing.",
        "width": 1600,
        "height": 1000
      },
      {
        "slug": "timetable",
        "title": "Timetable poster",
        "note": "One sheet for both terminals. The headline says the only thing anyone needs to remember.",
        "width": 1200,
        "height": 1500
      },
      {
        "slug": "pictograms",
        "title": "Pictogram set",
        "note": "Drawn on the same 120-unit grid as the logo, at the same stroke weight, so the ferry mark is one of the set.",
        "width": 1600,
        "height": 1000
      },
      {
        "slug": "type",
        "title": "Type and colour",
        "note": "",
        "width": 1600,
        "height": 1000
      }
    ]
  },
  "bakery": {
    "key": "bakery",
    "name": "Sandwich Town Bakery",
    "real": false,
    "what": "Concept: a bakery in Windsor's oldest neighbourhood",
    "year": "2026",
    "role": "Concept identity, bread bags, storefront, coasters",
    "brief": "A single ear of wheat in a butter-yellow coin. Instrument Serif italic keeps the wordmark warm without leaning on a script face, and one-colour printing keeps the bags cheap enough to give away with every loaf.",
    "palette": {
      "crust": "#8A4B1E",
      "flour": "#F7EEDF",
      "rye": "#3D2A1A",
      "butter": "#F3C96B",
      "oat": "#D9C7A6"
    },
    "fonts": {
      "display": "Instrument Serif Italic",
      "body": "Manrope"
    },
    "markLight": "<svg viewBox=\"0 0 120 120\" width=\"120\" height=\"120\" xmlns=\"http://www.w3.org/2000/svg\">\n      <circle cx=\"60\" cy=\"60\" r=\"52\" fill=\"#F3C96B\"/>\n      <path d=\"M60 104V30\" stroke=\"#3D2A1A\" stroke-width=\"4\" stroke-linecap=\"round\"/><path d=\"M0 0c6-4 12 0 12 8s-6 12-12 8c-6-4-6-12 0-16Z\" fill=\"#3D2A1A\" transform=\"translate(60 88) rotate(-60)\"/><path d=\"M0 0c6-4 12 0 12 8s-6 12-12 8c-6-4-6-12 0-16Z\" fill=\"#3D2A1A\" transform=\"translate(60 88) rotate(120)\"/><path d=\"M0 0c6-4 12 0 12 8s-6 12-12 8c-6-4-6-12 0-16Z\" fill=\"#3D2A1A\" transform=\"translate(60 74) rotate(-60)\"/><path d=\"M0 0c6-4 12 0 12 8s-6 12-12 8c-6-4-6-12 0-16Z\" fill=\"#3D2A1A\" transform=\"translate(60 74) rotate(120)\"/><path d=\"M0 0c6-4 12 0 12 8s-6 12-12 8c-6-4-6-12 0-16Z\" fill=\"#3D2A1A\" transform=\"translate(60 60) rotate(-60)\"/><path d=\"M0 0c6-4 12 0 12 8s-6 12-12 8c-6-4-6-12 0-16Z\" fill=\"#3D2A1A\" transform=\"translate(60 60) rotate(120)\"/><path d=\"M0 0c6-4 12 0 12 8s-6 12-12 8c-6-4-6-12 0-16Z\" fill=\"#3D2A1A\" transform=\"translate(60 46) rotate(-60)\"/><path d=\"M0 0c6-4 12 0 12 8s-6 12-12 8c-6-4-6-12 0-16Z\" fill=\"#3D2A1A\" transform=\"translate(60 46) rotate(120)\"/>\n      <path d=\"M60 30l-8-14M60 30l8-14M60 30v-16\" stroke=\"#3D2A1A\" stroke-width=\"3\" stroke-linecap=\"round\"/></svg>",
    "markDark": "<svg viewBox=\"0 0 120 120\" width=\"120\" height=\"120\" xmlns=\"http://www.w3.org/2000/svg\">\n      <circle cx=\"60\" cy=\"60\" r=\"52\" fill=\"#F3C96B\"/>\n      <path d=\"M60 104V30\" stroke=\"#3D2A1A\" stroke-width=\"4\" stroke-linecap=\"round\"/><path d=\"M0 0c6-4 12 0 12 8s-6 12-12 8c-6-4-6-12 0-16Z\" fill=\"#3D2A1A\" transform=\"translate(60 88) rotate(-60)\"/><path d=\"M0 0c6-4 12 0 12 8s-6 12-12 8c-6-4-6-12 0-16Z\" fill=\"#3D2A1A\" transform=\"translate(60 88) rotate(120)\"/><path d=\"M0 0c6-4 12 0 12 8s-6 12-12 8c-6-4-6-12 0-16Z\" fill=\"#3D2A1A\" transform=\"translate(60 74) rotate(-60)\"/><path d=\"M0 0c6-4 12 0 12 8s-6 12-12 8c-6-4-6-12 0-16Z\" fill=\"#3D2A1A\" transform=\"translate(60 74) rotate(120)\"/><path d=\"M0 0c6-4 12 0 12 8s-6 12-12 8c-6-4-6-12 0-16Z\" fill=\"#3D2A1A\" transform=\"translate(60 60) rotate(-60)\"/><path d=\"M0 0c6-4 12 0 12 8s-6 12-12 8c-6-4-6-12 0-16Z\" fill=\"#3D2A1A\" transform=\"translate(60 60) rotate(120)\"/><path d=\"M0 0c6-4 12 0 12 8s-6 12-12 8c-6-4-6-12 0-16Z\" fill=\"#3D2A1A\" transform=\"translate(60 46) rotate(-60)\"/><path d=\"M0 0c6-4 12 0 12 8s-6 12-12 8c-6-4-6-12 0-16Z\" fill=\"#3D2A1A\" transform=\"translate(60 46) rotate(120)\"/>\n      <path d=\"M60 30l-8-14M60 30l8-14M60 30v-16\" stroke=\"#3D2A1A\" stroke-width=\"3\" stroke-linecap=\"round\"/></svg>",
    "pieces": [
      {
        "slug": "bag",
        "title": "Bread bag",
        "note": "A paper bag with the mark printed once, large, and the loaf name in a window. One colour keeps it cheap enough to give away.",
        "width": 1600,
        "height": 1000
      },
      {
        "slug": "shopfront",
        "title": "Storefront",
        "note": "The Sandwich Street unit. Rye-brown fascia, flour lettering, butter awning.",
        "width": 1600,
        "height": 1000
      },
      {
        "slug": "stickers",
        "title": "Loaf stickers",
        "note": "Seals for the bags, one per loaf type.",
        "width": 1600,
        "height": 1000
      },
      {
        "slug": "menu",
        "title": "Menu board",
        "note": "Behind the counter, reprinted daily. The list is the design.",
        "width": 1200,
        "height": 1500
      },
      {
        "slug": "type",
        "title": "Type and colour",
        "note": "",
        "width": 1600,
        "height": 1000
      }
    ]
  }
};
export const designBrandList = brandOrder.map((k) => designBrands[k]);
